
'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export default function SchoolInfoPage() {
    return (
        <div className="space-y-8">
            <div>
                <h1 className="font-headline text-3xl font-bold">School Information</h1>
                <p className="text-muted-foreground">
                    Manage the school's general details.
                </p>
            </div>
            <Card>
                <CardHeader>
                    <CardTitle>Official School Details</CardTitle>
                    <CardDescription>
                        This page will contain a form to manage the school's core identity information. Administrators can update the official school name, address, contact numbers, email, and upload the official logo. This information will be used automatically in all official documents generated by the portal, such as letterheads, report cards, and invoices.
                         <br /><br />
                        <strong className="text-primary">This feature is currently in development and will be available once the project is approved.</strong>
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <Button disabled>Save Changes</Button>
                </CardContent>
            </Card>
        </div>
    );
}
